-- 코드를 입력하세요
SELECT O.ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS AS O JOIN (
SELECT ANIMAL_ID
FROM ANIMAL_INS 
WHERE SEX_UPON_INTAKE LIKE 'Intact%'
    ) AS I ON O.ANIMAl_ID = I.ANIMAl_ID
WHERE SEX_UPON_OUTCOME LIKE 'Spayed%' OR SEX_UPON_OUTCOME LIKE 'Neutered%'
ORDER BY O.ANIMAL_ID