# -- 코드를 입력하세요
SELECT  YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, user.GENDER, COUNT(distinct(user.USER_ID)) AS USERS
FROM USER_INFO AS user RIGHT JOIN ONLINE_SALE AS online ON user.USER_ID = online.USER_ID
WHERE user.GENDER IS NOT NULL
GROUP BY YEAR(online.SALES_DATE), MONTH(online.SALES_DATE), user.GENDER
ORDER BY YEAR(online.SALES_DATE), MONTH(online.SALES_DATE), user.GENDER

# SELECT *
# FROM USER_INFO
# WHERE USER_ID IN (
# SELECT USER_ID
# FROM ONLINE_SALE
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
#     ) AND GENDER IS NOT NULL
    
    
# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
# FROM ONLINE_SALE
# WHERE USER_ID IN ( SELECT USER_ID
#                  FROM USER_INFO
#                  WHERE GENDER IS NOT NULL)
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)