-- 코드를 입력하세요
WITH TBL AS(
SELECT CAR_ID, DATEDIFF(END_DATE,START_DATE)+1 AS cnt
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    )

SELECT CAR_ID, ROUND(SUM(cnt)/COUNT(CAR_ID),1) AS AVERAGE_DURATION
FROM TBL
GROUP BY CAR_ID
HAVING AVERAGE_DURATION >=7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC