WITH TBL AS (
    SELECT *
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)
, SalesCount AS (
    SELECT YEAR(SALES_DATE) AS YEAR, 
           MONTH(SALES_DATE) AS MONTH, 
           COUNT(DISTINCT S.USER_ID) AS PUCHASED_USERS
    FROM TBL 
    JOIN ONLINE_SALE AS S ON TBL.USER_ID = S.USER_ID
    GROUP BY YEAR, MONTH
)
, TotalCount AS (
    SELECT COUNT(DISTINCT USER_ID) AS TOTAL_USERS
    FROM TBL
)
SELECT 
    SC.YEAR, 
    SC.MONTH, 
    SC.PUCHASED_USERS, 
    ROUND((SC.PUCHASED_USERS / TC.TOTAL_USERS), 1) AS PUCHASED_RATIO
FROM 
    SalesCount AS SC
CROSS JOIN 
    TotalCount AS TC
ORDER BY SC.YEAR, SC.MONTH